### ISSUE TITLE
 No module named 'arc.arc_c_extensions'

### ISSUE THREAD

**Issue by linxiaodong902** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#54]
hey! @nikolasibalic 
 
I just download the ARC-Alkali-Rydberg-Calculator-3.0.2 .Running the code:

'atom= Strontium88()
calc = LevelPlot(atom)
calc.makeLevels(5,6,0,5,sList=[0,1])
calc.drawLevels()
calc.showPlot()'

in jupyter notebook (python 3.8). Return the error:

'ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-61b7ad57f101> in <module>
----> 1 atom= Strontium88()
      2 
      3 calc = LevelPlot(atom)
      4 calc.makeLevels(5,6,0,5,sList=[0,1])
      5 calc.drawLevels()

d:\Jupter\ARC\ARC-Alkali-Rydberg-Calculator-3.0.2\ARC-Alkali-Rydberg-Calculator-3.0.2\arc\divalent_atom_functions.py in __init__(self, preferQuantumDefects, cpp_numerov)
    104 
    105         if self.cpp_numerov:
--> 106             from .arc_c_extensions import NumerovWavefunction
    107             self.NumerovWavefunction = NumerovWavefunction
    108 

ModuleNotFoundError: No module named 'arc.arc_c_extensions''

Any ideas?
thanks!
lin

**Comment by nikolasibalic** [comment]
Hi @linxiaodong902 

For installation you should not directly download the code, but instead use pip from command line to install the latest package. That way you get necessary extension compiled for our operating system. So as detailed [here](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/installation.html), you should run

```pip install ARC-Alkali-Rydberg-Calculator ```

You will get latest package (currently 3.0.4).
Let me know if this resolves your problem.

**Comment by linxiaodong902** [comment]
Hi @nikolasibalic 

I run the code, but it return the error:



'Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "D:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "D:\anaconda3\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "D:\anaconda3\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "D:\anaconda3\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
    status = self.run(options, args)
  File "D:\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "D:\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 332, in run
    requirement_set = resolver.resolve(
  File "D:\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "D:\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "D:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 467, in prepare_linked_requirement
    local_file = unpack_url(
  File "D:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 255, in unpack_url
    file = get_http_url(
  File "D:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 129, in get_http_url
    from_path, content_type = _download_http_url(
  File "D:\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 281, in _download_http_url
    for chunk in download.chunks:
  File "D:\anaconda3\lib\site-packages\pip\_internal\cli\progress_bars.py", line 166, in iter
    for x in it:
  File "D:\anaconda3\lib\site-packages\pip\_internal\network\utils.py", line 15, in response_chunks
    for chunk in response.raw.stream(
  File "D:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\anaconda3\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out'


Any ideas?
thanks!

**Comment by nikolasibalic** [comment]
Just to confirm, you run ```pip install ARC-Alkali-Rydberg-Calculator ``` from Command Prompt on Windows?

This error has nothing to do with ARC. It tells you that the ```pip``` package manager did not managed to establish connection with files.pythonhosted.org which might be due to the glitch on your internet connection. Basically it tried to established https connection with files.pythonhosted.org and failed.

Just check internet connection and try again. You can try installing something else with pip too, to be sure it's not ARC related problem, but I am quite sure it's not. Let me knows if it works.

**Comment by linxiaodong902** [comment]
Thank you!
Problem solved!
