### ISSUE TITLE
LevelPlot - interactivity throws error after 2 clicks

### ISSUE THREAD

**Issue by petermao** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#70]
LevelPlot interactivity only works for 2 clicks.  See below for details
```
import arc

levels = arc.LevelPlot(arc.Cesium())
levels.makeLevels(99,101,1,3)
levels.drawLevels(units='ghz')
levels.showPlot()
```
click on 2 levels: title shows states and delta E
3rd click: no response
4th click: error message shows up
```
In [5]: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/Users/xxxx/Library/Python/3.7/lib/python/site-packages/arc/calculations_atom_single.py", line 1777, in onpick2
    self.state1[2], s=self.state1[3]),
IndexError: list index out of range
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/Users/xxxx/Library/Python/3.7/lib/python/site-packages/arc/calculations_atom_single.py", line 1777, in onpick2
    self.state1[2], s=self.state1[3]),
IndexError: list index out of range
```
(running 3.0.14)

My python-fu is not adequate to resolve this issue.

**Comment by nikolasibalic** [comment]
Thanks @petermao for spotting this, that used to work in the past but something got messed up in meantime it seems.

It works now in 3.0.15. with one caveat: you cannot choose two states wish same n and l in sequence of two clicks (e.g. one cannot select 8 P_1/2 -> 8 P_3/2  transition, but one can select e.g. 8 P_1/2 -> 10 P_3/2 or transitions between different l ).
